# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=255)),
                ('num_casa', models.IntegerField()),
            ],
        ),
    ]
